<a href="https://colab.research.google.com/github/daawonn/ml_dl_projects/blob/master/1_tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 목적

-  텐서플로우 기본 사용법을 익힌다 


In [0]:
import tensorflow as tf
%tensorflow_version 1.x

# 기본틀
- 그래프
- 연산(계산) 처리

In [0]:
# A. 관계 기술 => 그래프 => 플로우(흐름)을 구성
hello = tf.constant('hello DL !!') # 상수
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [0]:
# B. 구동
# 1. 세션을 구한다(오픈한다)
sess = tf.Session()
# 2. 데이터를 주입하여 연산(계산)
print(sess.run( hello ))
# 3. 세션을 닫는다
sess.close()

b'hello DL !!'

In [0]:
# I/O 처리시 close()를 누락할 수도 있기 때문에 with문 사용해서 두 줄로 줄이기
with tf.Session() as sess:
  print(sess.run( hello ))

b'hello DL !!'


# 텐서플로우를 이용한 간단한 연산(계산)

In [0]:
# 1. 플로우 구성

# 상수 정의(define)
a = tf.constant(123)
b = tf.constant(500)
a,b

(<tf.Tensor 'Const_1:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_2:0' shape=() dtype=int32>)

In [0]:
# 계산 정의(실제로 수행은 하지않고 더한다는 형태만 가진다)
add_operation = a + b
add_operation

<tf.Tensor 'add:0' shape=() dtype=int32>

In [0]:
# 실제 연산 처리, 구동
with tf.Session() as sess:
  res = sess.run( add_operation )
  print( res, type(res) )

623 <class 'numpy.int32'>


# 텐서플로우의 기본 항목 사용

- 핵심 데이터 구조 요소
  - 상수 : Constant
  - 변수 : Variable
  - 플레이스홀더 : Placeholder


In [0]:
# 상수 정의
a = tf.constant( 100, name='a' )
b = tf.constant( 110, name='b' ) 
c = tf.constant( 120, name='c' )
a,b,c

(<tf.Tensor 'a:0' shape=() dtype=int32>,
 <tf.Tensor 'b:0' shape=() dtype=int32>,
 <tf.Tensor 'c:0' shape=() dtype=int32>)

In [0]:
# 변수 정의
v = tf.Variable( 0, name='v' )
v, v.name

(<tf.Variable 'v_1:0' shape=() dtype=int32_ref>, 'v_1:0')

In [0]:
# 연산식 정의 : 데이터 플로우 그래프의 정의
calc_operation  = a + b + c
calc_operation

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
# 데이터 플로우 그래프의 정의
# 변수 v 에 calc_operation의 계산값을 대입(assign)하라는 그래프를 정의
assign_operation = tf.assign( v, calc_operation )
assign_operation

<tf.Tensor 'Assign:0' shape=() dtype=int32_ref>

In [0]:
# 구동
with tf.Session() as sess:
  res = sess.run( assign_operation )
  print( res, type(res) )
  res = sess.run(v)
  print( res, type(res) )

330 <class 'numpy.int32'>
330 <class 'numpy.int32'>


## 플레이스홀더
  - 템플릿 같은 느낌
  - 데이터 플로우 그래프(관계) 구축시 값을 넣지 않고 값을 담을 수 있는 형태만 정의한 형식
  - 세션 수행시 데이터가 담긴다(함수호출시 인자를 전달할때 받는 파라미터의 느낌, 데이터를 주입시 받는 공간,그릇)
  - SQL문 수행시 ?, %s 등을 통해서 파라미터를 전달하는 느낌과 비슷하다

In [0]:
# 고정크기 플레이스홀더
# 정수값 3개가 올 수 있다
a = tf.placeholder(tf.int32, [3])   # 여기서 3은 배열,1차원
a

<tf.Tensor 'Placeholder:0' shape=(3,) dtype=int32>

In [0]:
# 상수
b = tf.constant( 2 )

In [0]:
# 데이터 플로우 그래프
# 벡터(a)와 스칼라(b)의 연산
x2_operation = a * b 

In [0]:
# 연산수행
with tf.Session() as sess:
  res = sess.run( x2_operation, feed_dict={ a :[1,2,3] } )
  print(res, type(res)) # ndarray는 리스트와 다르게 값사이에 ',' 가 없음

[2 4 6] <class 'numpy.ndarray'>


In [0]:
# 가변크기 플레이스홀더
# 크기를 모를때, 크기를 다양하게 받을때
a = tf.placeholder(tf.int32, [None])
b = tf.constant( 3 )
x3_operation = a * b 

In [0]:
# 연산수행
with tf.Session() as sess:
  # 주입하는 데이터의 shape이 다르다
  res = sess.run( x3_operation, feed_dict={ a :[1,2,3,4] } )
  print(res, type(res))
  res = sess.run( x3_operation, feed_dict={ a :[10,11] } )
  print(res, type(res)) 

[ 3  6  9 12] <class 'numpy.ndarray'>
[30 33] <class 'numpy.ndarray'>


# 세션 구동

- Session()
- InteractiveSession()
  - run()을 사용하지 않는다
  - 처리시 eval()함수를 활용
  

In [0]:
sess = tf.InteractiveSession()

In [0]:
matrix1 = tf.constant( [ [1.,2.], [3.,4.] ] )
matrix2 = tf.constant( [ [10.], [20.] ] )
matrix1, matrix2 , matrix1.shape, matrix2.shape

(<tf.Tensor 'Const_10:0' shape=(2, 2) dtype=float32>,
 <tf.Tensor 'Const_11:0' shape=(2, 1) dtype=float32>,
 TensorShape([Dimension(2), Dimension(2)]),
 TensorShape([Dimension(2), Dimension(1)]))

In [0]:
# 행렬의 곱
tf.matmul( matrix1, matrix2 ).eval()

array([[ 50.],
       [110.]], dtype=float32)

In [0]:
(matrix1 * matrix2).eval()

array([[10., 20.],
       [60., 80.]], dtype=float32)

In [0]:
sess.close()